# Generated by Django 6.0.6 on 2026-06-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('educational_qualification', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('tenure', models.IntegerField(help_text='Tenure in years')),
                ('monthly_salary', models.IntegerField(help_text='Salary in BDT')),
                ('incentive_earnings', models.FloatField()),
                ('attendance_pct', models.FloatField(help_text='Attendance Percentage')),
                ('leave_utilization', models.IntegerField(help_text='Days of leave utilized')),
                ('distance_from_workplace', models.IntegerField(help_text='Distance in km')),
                ('num_transfers', models.IntegerField()),
                ('performance_rating', models.IntegerField(help_text='Rating 1-5')),
                ('training_hours', models.IntegerField()),
                ('promotion_history', models.IntegerField(help_text='Number of promotions')),
                ('manager_effectiveness_score', models.IntegerField(help_text='Score 1-10')),
                ('employee_engagement_score', models.IntegerField(help_text='Score 1-10')),
                ('overtime_hours', models.IntegerField(help_text='Overtime hours per month')),
                ('previous_attrition_label', models.CharField(help_text="'Yes' or 'No'", max_length=10)),
                ('attrition_probability', models.FloatField(blank=True, help_text='0.0 to 1.0', null=True)),
                ('risk_category', models.CharField(blank=True, help_text="'Low', 'Medium', 'High'", max_length=20, null=True)),
                ('primary_driver', models.CharField(blank=True, help_text="XAI output e.g., 'Excessive Overtime'", max_length=255, null=True)),
            ],
        ),
    ]
