# Generated by Django 6.0.6 on 2026-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='risk_category',
            field=models.CharField(blank=True, help_text="'Low', 'Medium', 'High'", max_length=10, null=True),
        ),
    ]
